### ISSUE TITLE
Error with shared credentials

### ISSUE THREAD

**Issue by tb102122** [rewindio/terraform-rewindio-example#2]
Dear all,

thanks for the great article. I am currently getting an error with the version v0.80 due to AWS credentials not valid.
Any idea what is wrong with my action setup?
Extract from my action:

`      - name: Setup AWS Credentials
        run: |
          mkdir -p .aws
          echo "[stage]" >> .aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}" >> .aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}" >> .aws/credentials
          echo "[prod]" >> .aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}" >> .aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}" >> .aws/credentials
      - name: Terraform Init
        uses: rewindio/terraform-github-actions@v0.8.0
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: init
          tf_actions_working_dir: "02_terraform"
          args: -backend-config ${{ steps.tfvars.outputs.backend }}
        env:
          AWS_SHARED_CREDENTIALS_FILE: $GITHUB_WORKSPACE/.aws/credentials
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`

When I run the code the output looks the following:

 Terraform Init6s
init: info: commenting on the pull request
/usr/bin/docker run --name cb5cf5cbcca1d94595b568e984ca6a502e_f4d7eb --label 8118cb --workdir /github/workspace --rm -e TF_VERSION -e AWS_SHARED_CREDENTIALS_FILE -e GITHUB_TOKEN -e TF_VAR_github_token -e TF_VAR_AUTH_TOKEN -e TF_VAR_USER_ID -e INPUT_TF_ACTIONS_VERSION -e INPUT_TF_ACTIONS_SUBCOMMAND -e INPUT_TF_ACTIONS_WORKING_DIR -e INPUT_ARGS -e INPUT_TF_ACTIONS_CLI_CREDENTIALS_HOSTNAME -e INPUT_TF_ACTIONS_CLI_CREDENTIALS_TOKEN -e INPUT_TF_ACTIONS_COMMENT -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/REPONAME/REPONAME":"/github/workspace" 8118cb:5cf5cbcca1d94595b568e984ca6a502e -backend-config tfvars/dev/backend.tfvars
Downloading Terraform v0.12.29
Successfully downloaded Terraform v0.12.29
Unzipping Terraform v0.12.29
Successfully unzipped Terraform v0.12.29
init: info: initializing Terraform configuration in 02_terraform
**init: error: failed to initialize Terraform configuration in 02_terraform**
Initializing modules...

...download of modules...

Initializing the backend...

**Error: No valid credential sources found for AWS Provider.
	Please see https://terraform.io/docs/providers/aws/index.html for more information on
	providing credentials for the AWS Provider**

See the errors marked in bold which are not working.
Thanks for your help!
Cheers Tobias

**Comment by tayyabqadir877** [comment]
are you working for rewind.io ?

**Comment by tb102122** [comment]
No I am not and I resolved it today. My path was not correct.
